services:
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4
    container_name: lavalink-chopsticks
    restart: unless-stopped
    ports:
      - "2333:2333"
    volumes:
      - ./lavalink/config/application.yml:/opt/Lavalink/application.yml:ro
      - ./lavalink/config/plugins:/opt/Lavalink/plugins:ro
