global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "chopsticks"
    static_configs:
      - targets: ["host.docker.internal:9100"]
        labels:
          role: "bot"

  - job_name: "woksite_website"
    metrics_path: /api/metrics
    static_configs:
      - targets: ["woksite-website:3000"]

  - job_name: "woksite_websocket"
    metrics_path: /metrics
    static_configs:
      - targets: ["woksite-websocket-server:3002"]

  - job_name: "woksite_postgres"
    static_configs:
      - targets: ["woksite-postgres-exporter:9187"]

  - job_name: "woksite_redis"
    static_configs:
      - targets: ["woksite-redis-exporter:9121"]
